### ISSUE TITLE
Hyundai Ioniq

### ISSUE THREAD

**Issue by erkkiat** [chargeprice/open-ev-data#5]
Hi again!

Would you also please add the Hyundai Ioniq models? 

https://www.hyundai.co.uk/new-cars/ioniq/electric

-- Eki

**Comment by erkkiat** [comment]
Sorry, my mistake. My filter took out below 50 kW DC chargers... Didn't the 2019-2020 Ioniq charge at 100 kW?

**Comment by hoenic07** [comment]
Doesn't look like it.. https://insideevs.com/news/381451/hyundai-ioniq-electric-disappoints-dc-charging-power/
